import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { join, resolve, relative, isAbsolute } from 'node:path'
import { createRequire } from 'node:module'
import { randomUUID, createHash } from 'node:crypto'
const require = createRequire(import.meta.url)
const { createDurableImageCustody, custodyFileIO } = require('../../shell/durable-image-custody.cjs')
const { createImageOutbox } = require('../../shell/image-outbox.cjs')
const enabled = !!process.env.IMAGE_CLEANUP_TEST_ROOT
const skip = enabled ? false : 'Explicit cleanup approval and IMAGE_CLEANUP_TEST_ROOT fixture are required; no cleanup executed.'
function fixture() {
  const root = resolve(process.env.IMAGE_CLEANUP_TEST_ROOT)
  // Exact precreated approval target; digest avoids embedding an account path in source.
  assert.equal(createHash('sha256').update(root).digest('hex'), 'd0ca2c9620be70537d060d83e4a204a534c3923a21bfbc34df128b518d639aef', 'root is not the reviewed cleanup fixture')
  custodyFileIO.plain(root, true)
  assert.equal(fs.realpathSync(root), root, 'cleanup root must be its literal real path')
  const markerPath = join(root, 'fixture-owner.json')
  custodyFileIO.plain(markerPath, false)
  assert.equal(fs.realpathSync(markerPath), markerPath, 'marker must be its literal real path')
  const marker = JSON.parse(fs.readFileSync(markerPath, 'utf8'))
  assert.deepEqual(marker, { task: 'T489', worker: '9542bfe2', purpose: 'fresh harmless image retention cleanup tests' })
  const child = fs.mkdtempSync(join(root, 'owned-run-'))
  assert.ok(relative(root, child) && !relative(root, child).startsWith('..') && !isAbsolute(relative(root, child)))
  custodyFileIO.plain(child, true)
  assert.equal(fs.realpathSync(child), child)
  const byteRoot = join(child, 'custody'); const outboxRoot = join(child, 'outbox')
  fs.mkdirSync(byteRoot); fs.mkdirSync(outboxRoot)
  fs.writeFileSync(join(child, 'ownership.json'), JSON.stringify({ task: 'T489', root, child, purpose: 'synthetic generated bytes only' }))
  const context = { owner: 'fixture-owner', epoch: 1 }
  const authenticate = c => ({ authenticated: c?.epoch === 1, productOwnerId: c?.owner })
  const bindings = new Map()
  const makeCustody = () => createDurableImageCustody({ root: byteRoot, authenticate, authorizeCandidate: () => true,
    authorizeRelease: ({ receipt }) => bindings.get(receipt.id) })
  const custody = makeCustody()
  const outboxOptions = { root: outboxRoot, conversationId: 'fixture-conversation', authenticate, authorizeCompaction: () => true,
    authorizeTransfer: () => true, validateReceipt: r => custody.reopen(r, context).images.length }
  const outbox = createImageOutbox(outboxOptions)
  const bytes = Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7', 'base64')
  const retain = () => custody.retain({ operationId: randomUUID(), conversationId: 'fixture-conversation', accountId: 'fixture-account',
    provider: 'codex', images: [{ mime: 'image/gif', bytes }] }, context)
  return { child, byteRoot, outboxRoot, context, bindings, custody, makeCustody, outbox, outboxOptions, bytes, retain }
}
function op(store, context) { return { operationId: randomUUID(), expectedGeneration: store.read(context).generation } }
test('approved fixture only: capacity reuse beyond 12 assets and 256 revisions preserves unknown bytes', { skip }, () => {
  const h = fixture()
  const unknownReceipt = h.retain()
  h.bindings.set(unknownReceipt.id, { state: 'unknown', referenceOwners: ['outbox'] })
  const unknown = h.outbox.admit({ ...op(h.outbox, h.context), text: '', imageReceipts: [unknownReceipt] }, h.context).entries[0]
  h.outbox.write({ ...op(h.outbox, h.context), entries: [{ ...unknown, state: 'unknown' }] }, h.context)
  assert.throws(() => h.custody.releaseAccepted(unknownReceipt, h.context), { code: 'IMAGE_CUSTODY_RELEASE_REFUSED' })
  let retired = null
  let completed = 0
  let revisions = 2
  for (let i = 0; i < 70; i++) {
    const receipt = h.retain()
    h.bindings.set(receipt.id, { state: 'accepted', referenceOwners: ['transcript','live-session'] })
    assert.throws(() => h.custody.releaseAccepted(receipt, h.context), { code: 'IMAGE_CUSTODY_RELEASE_REFUSED' })
    let result = h.outbox.admit({ ...op(h.outbox, h.context), text: 'fixture turn ' + i, imageReceipts: [receipt] }, h.context)
    const queued = result.entries.at(-1)
    result = h.outbox.write({ ...op(h.outbox, h.context), entries: result.entries.map(e => e.envelopeId === queued.envelopeId ? { ...e, state: 'unknown' } : e) }, h.context)
    result = h.outbox.write({ ...op(h.outbox, h.context), entries: result.entries.map(e => e.envelopeId === queued.envelopeId ? { ...e, state: 'accepted' } : e) }, h.context)
    h.outbox.retireAccepted({ ...op(h.outbox, h.context), envelopeIds: [queued.envelopeId] }, h.context)
    revisions += 4
    h.bindings.set(receipt.id, { state: 'accepted', referenceOwners: [] })
    h.custody.releaseAccepted(receipt, h.context)
    completed++
    retired = queued
    if (i % 8 === 7) h.outbox.compact(op(h.outbox, h.context), h.context)
    assert.equal(h.outbox.read(h.context).entries[0].state, 'unknown')
  }
  const beforeCompact = h.outbox.read(h.context)
  h.outbox.compact(op(h.outbox, h.context), h.context)
  const reopened = createImageOutbox(h.outboxOptions).read(h.context)
  assert.equal(reopened.entries.length, 1)
  assert.equal(reopened.entries[0].state, 'unknown')
  assert.equal(reopened.automaticSend, false)
  assert.throws(() => h.outbox.write({ operationId: randomUUID(), expectedGeneration: beforeCompact.generation, entries: beforeCompact.entries }, h.context), { code: 'IMAGE_OUTBOX_STALE' })
  assert.throws(() => h.outbox.write({ ...op(h.outbox, h.context), entries: [...reopened.entries, retired] }, h.context), { code: 'IMAGE_OUTBOX_ADMISSION_REQUIRED' })
  const images = h.makeCustody().reissue(unknownReceipt, { conversationId: 'fixture-conversation', accountId: 'fixture-account',
    provider: 'codex', productOwnerId: h.context.owner, sessionId: 'fixture-reopened' }, h.context).images
  assert.deepEqual(fs.readFileSync(images[0].path), h.bytes)
  assert.ok(completed > 12 && revisions > 256)
  const receipt = { fixture: h.child, completed, revisions, unknownPreserved: true,
    remainingByteReservations: fs.readdirSync(h.byteRoot).length, remainingOutboxFiles: fs.readdirSync(h.outboxRoot).length }
  fs.writeFileSync(join(h.child, 'cleanup-receipt.json'), JSON.stringify(receipt))
  console.log('CLEANUP_RECEIPT ' + JSON.stringify(receipt))
})
test('approved fixture only: interrupted compaction preserves prior entries and resumes exact operation', { skip }, () => {
  const h = fixture()
  const first = h.outbox.admit({ ...op(h.outbox, h.context), text: 'cancel me', imageReceipts: [] }, h.context)
  const queued = first.entries[0]
  h.outbox.cancel({ ...op(h.outbox, h.context), envelopeIds: [queued.envelopeId] }, h.context)
  h.outbox.retireAccepted({ ...op(h.outbox, h.context), envelopeIds: [queued.envelopeId] }, h.context)
  const request = op(h.outbox, h.context)
  const unlink = fs.unlinkSync
  let calls = 0
  fs.unlinkSync = file => {
    assert.ok(relative(h.outboxRoot, file) && !relative(h.outboxRoot, file).startsWith('..'))
    if (++calls === 2) throw Object.assign(new Error('fixture interrupted cleanup'), { code: 'EIO' })
    return unlink(file)
  }
  try { assert.throws(() => h.outbox.compact(request, h.context), { code: 'EIO' }) }
  finally { fs.unlinkSync = unlink }
  const reopened = createImageOutbox(h.outboxOptions)
  assert.equal(reopened.read(h.context).writeBlocked, 'IMAGE_OUTBOX_CLEANUP_REQUIRED')
  assert.throws(() => reopened.admit({ ...op(reopened, h.context), text: 'blocked', imageReceipts: [] }, h.context), { code: 'IMAGE_OUTBOX_CLEANUP_REQUIRED' })
  const result = reopened.compact(request, h.context)
  assert.equal(result.entries.length, 0)
  assert.throws(() => reopened.write({ ...op(reopened, h.context), entries: [queued] }, h.context), { code: 'IMAGE_OUTBOX_ADMISSION_REQUIRED' })
  const after = reopened.admit({ ...op(reopened, h.context), text: 'fresh deliberate work', imageReceipts: [] }, h.context)
  assert.equal(after.entries.length, 1)
  assert.equal(after.automaticSend, false)
})
