// A FILE THAT DIES AT IMPORT MUST COST ITSELF, NOT THE RUN'S VERDICT.
//
// MEASURED on the 1.0.45 strict run of 2026-09-17: 14151 tests reported, exactly
// ONE ordinal break, and the ratchet exited 2 -- "TAP result ordinal is missing,
// duplicated, or out of order" -- having measured nothing at all. The cause was
// tools/test/paste-picture-reaches-the-turn.test.mjs asserting at IMPORT that
// MC_T18_ENGINE_ROOT or MC_CANONICAL_ROOT named the engine checkout. Neither was
// set, so node:test emitted a FILE-level result numbered from the FILE counter
// (703) while the parser was counting TESTS (7365 next).
//
// Exit 2 is the documented measured-nothing path, so the gate worked. But a cut
// meeting this at seal time stops with neither a pass nor a fail, which is the
// worst of the three answers: nothing to fix and nothing to ship.
//
// THE FIXTURES BELOW ARE THE REAL SHAPE, NOT AN INVENTED ONE. Generated by
// running node --test over two files, one with two passing tests and one that
// throws at import:
//
//   ok 1 - one
//   ok 2 - two
//   not ok 2 - b.test.mjs      <- the FILE counter, duplicating a test ordinal
//   1..3
//   # tests 3 / # pass 2 / # fail 1
//
// Note what that shows and an invented fixture would have missed: the
// file-level result IS in the plan and in the summary counts. Only its ORDINAL
// is untrustworthy. A first version of this fix skipped the count increment and
// merely traded the ordinal refusal for the plan one.

import test from 'node:test'
import assert from 'node:assert/strict'

import { validateSuiteResult } from '../lib/test-suite-result.mjs'

/* Driven through the PUBLIC entry the ratchet calls, not an exported internal,
 * so what is proved here is what the cut will do. It also cross-checks the
 * process exit against the TAP fail count, so each fixture supplies the exit a
 * real run would have produced. */
const summary = ({ tests, pass, fail, skipped = 0 }) => [
  `# tests ${tests}`, '# suites 0', `# pass ${pass}`, `# fail ${fail}`,
  '# cancelled 0', `# skipped ${skipped}`, '# todo 0',
]

function realWorldTap({ verb = 'not ok', name = 'b.test.mjs', ordinal = 2 } = {}) {
  return [
    'TAP version 13',
    'ok 1 - one',
    'ok 2 - two',
    `${verb} ${ordinal} - ${name}`,
    '1..3',
    ...summary({ tests: 3, pass: verb === 'ok' ? 3 : 2, fail: verb === 'ok' ? 0 : 1 }),
  ].join('\n')
}

test('a file that dies at import is a named red and the run still yields a verdict', () => {
  const measured = validateSuiteResult({ code: 1, stdout: realWorldTap() })
  assert.equal(measured.counts.tests, 3, 'every test is still accounted for')
  assert.equal(measured.counts.pass, 2)
  assert.equal(measured.counts.fail, 1, 'the dead file is the one failure')
})

test('the same output refused before this fix, which is why the cut could stop with nothing', () => {
  // The discriminator is the ordinal alone: same shape, same counts, but the
  // file-level line renumbered so it is in order needs no exemption at all.
  const inOrder = [
    'TAP version 13',
    'ok 1 - one',
    'ok 2 - two',
    'not ok 3 - b.test.mjs',
    '1..3',
    ...summary({ tests: 3, pass: 2, fail: 1 }),
  ].join('\n')
  const measured = validateSuiteResult({ code: 1, stdout: inOrder })
  assert.equal(measured.counts.fail, 1, 'an in-order file-level failure was never the problem')
})

test('a file-level PASS with a broken ordinal is still refused', () => {
  // Fail-closed, and this asymmetry is what makes the exemption safe: admitting
  // an extra RED can only block a release, while admitting an unexplained GREEN
  // is the exact failure the ordinal rule exists to prevent.
  assert.throws(
    () => validateSuiteResult({ code: 0, stdout: realWorldTap({ verb: 'ok' }) }),
    /ordinal is missing, duplicated, or out of order/,
    'a green may never arrive out of order, whatever it is named',
  )
})

test('an ordinary test with a broken ordinal is still refused', () => {
  assert.throws(
    () => validateSuiteResult({ code: 1, stdout: realWorldTap({ name: 'an ordinary test description' }) }),
    /ordinal is missing, duplicated, or out of order/,
    'the exemption is for suite-file results only; spliced output stays refused',
  )
})

test('a nested result that merely looks like a file path is still refused', () => {
  // Indented, so it is a subtest and not node:test's file-level line. A test
  // free to name itself after a file must not be able to buy the exemption.
  const nested = [
    'TAP version 13',
    'ok 1 - one',
    'ok 2 - two',
    '    not ok 2 - b.test.mjs',
    '1..3',
    ...summary({ tests: 3, pass: 2, fail: 1 }),
  ].join('\n')
  assert.throws(
    () => validateSuiteResult({ code: 1, stdout: nested }),
    /ordinal is missing, duplicated, or out of order|plan is missing/,
    'only a top-level result can be the file-level one',
  )
})

test('the divergence scales: a file counter far behind the test counter', () => {
  // The real run's shape -- file 703 against test 7365 -- rather than the
  // two-file minimum. The gap size must not matter.
  const wide = [
    'TAP version 13',
    ...Array.from({ length: 5 }, (unused, index) => `ok ${index + 1} - test ${index + 1}`),
    'not ok 2 - tools/test/paste-picture-reaches-the-turn.test.mjs',
    '1..6',
    ...summary({ tests: 6, pass: 5, fail: 1 }),
  ].join('\n')
  const measured = validateSuiteResult({ code: 1, stdout: wide })
  assert.equal(measured.counts.fail, 1)
  assert.equal(measured.counts.tests, 6)
})
