import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, readFile, realpath } from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import { chromium } from 'playwright'
import { createResearchDataServer } from './research-data-server.mjs'

const temp = process.env.RESEARCH_QA_TEMP || os.tmpdir()
const resolved = await realpath(temp), home = await realpath(os.homedir())
const within = (child, parent) => { const rel = path.relative(parent, child); return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel)) }
// The QA only ever writes under the running account's own directories.
if (!within(resolved, home) && !within(resolved, await realpath(os.tmpdir()))) throw new Error(`QA temp boundary refused: ${resolved} is outside ${home}.`)
process.env.TEMP = resolved; process.env.TMP = resolved
const output = await mkdtemp(path.join(resolved, 'research-data-qa-')), data = path.join(output, 'generic-study')
await mkdir(data)
const descriptor = { name: 'sensor-study', title: 'Sensor measurements', resources: [{ name: 'observations', path: 'measurements.csv', schema: { fields: [{ name: 'timestamp', type: 'datetime' }, { name: 'sample_id', type: 'integer' }, { name: 'label', type: 'string' }, { name: 'reading', type: 'number' }], primaryKey: ['sample_id'] } }] }
await writeFile(path.join(data, 'datapackage.json'), JSON.stringify(descriptor))
await writeFile(path.join(data, 'notes.md'), '# Study notes\nA generic dataset used to test the research workspace.\n')
await writeFile(path.join(data, 'samples.csv'), 'sample_id,location\n1,North\n2,South\n')
await writeFile(path.join(data, 'measurements.csv'), 'timestamp,sample_id,label,reading\n' + Array.from({ length: 205 }, (_, i) => `2026-01-01T12:${String(Math.floor(i / 60)).padStart(2, '0')}:${String(i % 60).padStart(2, '0')}Z,${i},${i === 0 ? '<img src=x onerror=alert(1)>' : i % 2 ? 'sample-a' : 'sample-b'},${i === 204 ? 'invalid' : i / 10}\n`).join(''))
const origin = process.env.RESEARCH_QA_URL || 'http://127.0.0.1:4623'
const server = await createResearchDataServer({ root: data, origin, packages: ['datapackage.json'] })
const base = `http://127.0.0.1:${server.address().port}`
let browser
try {
  assert.equal((await fetch(base + '/workspace', { headers: { Origin: 'https://unrelated.example' } })).status, 403)
  assert.equal((await fetch(base + '/file?path=..%2Foutside.txt')).status, 400)
  assert.equal((await fetch(base + '/workspace', { method: 'POST' })).status, 405)
  browser = await chromium.launch({ headless: true, executablePath: process.env.RESEARCH_QA_CHROMIUM || undefined })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, timezoneId: 'America/Los_Angeles' }), errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/research-workspace.json', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ url: base }) }))
  await page.goto(origin + '/#/research', { waitUntil: 'domcontentloaded', timeout: 60000 })
  const dismiss = page.getByRole('button', { name: 'Not now', exact: true })
  await dismiss.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {})
  if (await dismiss.isVisible()) await dismiss.click()
  await page.locator('button[data-research-area="data"]').click()
  await page.locator('[data-rd-grid] tbody tr').first().waitFor()
  assert.equal(await page.locator('[data-rd-grid] tbody tr').count(), 100)
  assert.match(await page.locator('[data-rd-grid]').innerText(), /<img src=x onerror=alert\(1\)>/)
  assert.equal(await page.locator('[data-rd-grid] img').count(), 0)
  assert.equal(await page.locator('[data-rd-prev]').isDisabled(), true)
  await page.screenshot({ path: path.join(output, 'sheet.png'), fullPage: true })
  await page.locator('[data-rd-tab="chart"]').click()
  assert.match(await page.locator('[data-rd-chart-note]').innerText(), /Multiple categories in label/)
  assert.equal(await page.locator('[data-rd-chart] svg').count(), 0, 'Mixed categories must not silently become one line')
  await page.locator('[data-rd-series]').selectOption('2')
  await page.locator('[data-rd-chart] svg').waitFor()
  assert.match(await page.locator('[data-rd-chart]').getAttribute('aria-label'), /3 separate series grouped by label/)
  assert.equal(await page.locator('[data-rd-chart] img').count(), 0)
  await page.screenshot({ path: path.join(output, 'grouped-chart.png'), fullPage: true })
  await page.locator('[data-rd-series]').selectOption('auto')
  assert.equal(await page.locator('[data-rd-chart] svg').count(), 0)
  await page.locator('[data-rd-chart-kind]').selectOption('scatter')
  await page.locator('[data-rd-chart] svg').waitFor()
  await page.locator('[data-rd-chart-kind]').selectOption('line')
  assert.equal(await page.locator('[data-rd-chart] svg').count(), 0)
  await page.locator('[data-rd-series]').selectOption('all')
  await page.locator('[data-rd-chart] svg').waitFor()
  assert.match(await page.locator('[data-rd-chart]').getAttribute('aria-label'), /; 1 series\./)
  await page.locator('[data-rd-series]').selectOption('auto')
  await page.locator('[data-rd-tab="sheet"]').click()
  await page.locator('[data-rd-next]').click()
  await page.waitForFunction(() => document.querySelector('[data-rd-page]')?.textContent.startsWith('101'))
  await page.locator('[data-rd-next]').click()
  await page.waitForFunction(() => document.querySelector('[data-rd-page]')?.textContent.startsWith('201'))
  assert.equal(await page.locator('[data-rd-grid] tbody tr').count(), 5)
  await page.locator('[data-rd-errors-title]').click()
  assert.match(await page.locator('[data-rd-errors-list]').innerText(), /Row 206.*reading/)
  await page.locator('[data-rd-search]').fill('sample-a'); await page.locator('[data-rd-search-go]').click()
  await page.waitForFunction(() => document.querySelector('[data-rd-grid] tbody tr td:nth-child(4)')?.textContent === 'sample-a')
  await page.locator('[data-rd-tab="chart"]').click()
  await page.locator('[data-rd-y]').selectOption('3')
  await page.locator('[data-rd-chart] svg').waitFor()
  assert.match(await page.locator('[data-rd-chart] svg').textContent(), /12:/, 'Timestamp axis must display UTC even in a Pacific-time browser')
  await page.screenshot({ path: path.join(output, 'chart.png'), fullPage: true })
  await page.locator('[data-rd-validate]').click()
  await page.waitForFunction(() => document.querySelector('[data-rd-validation]')?.textContent.includes('205 rows checked'))
  assert.match(await page.locator('[data-rd-validation]').innerText(), /1 errors/)
  await page.locator('[data-rd-entry="notes.md"]').click()
  await page.waitForFunction(() => document.querySelector('[data-rd-file-text]')?.textContent.includes('generic dataset'))
  await page.locator('[data-rd-entry="measurements.csv"]').click()
  await page.locator('[data-rd-setup]').waitFor({ state: 'visible' })
  await page.locator('[data-rd-field-type="0"]').selectOption('datetime')
  await page.locator('[data-rd-field-type="1"]').selectOption('integer')
  await page.locator('[data-rd-field-type="3"]').selectOption('number')
  await page.locator('[data-rd-apply-schema]').click()
  await page.locator('[data-rd-tab="sheet"]').click()
  await page.locator('[data-rd-grid] tbody tr').first().waitFor()
  assert.match(await page.locator('[data-rd-grid] thead').innerText(), /datetime/)
  assert.equal(await page.locator('[data-rd-resource]').count(), 1)
  await page.locator('[data-rd-entry="samples.csv"]').click()
  await page.locator('[data-rd-setup]').waitFor({ state: 'visible' })
  await page.locator('[data-rd-field-type="0"]').selectOption('integer')
  await page.locator('[data-rd-apply-schema]').click()
  await page.waitForFunction(() => document.querySelector('[data-rd-sheet-title]')?.textContent === 'samples')
  assert.equal(await page.locator('[data-rd-resource]').count(), 2)
  const exporting = page.waitForEvent('download'); await page.locator('[data-rd-export]').click()
  const exported = await exporting; assert.equal(exported.suggestedFilename(), 'datapackage.json')
  const exportPath = path.join(output, 'exported-datapackage.json'); await exported.saveAs(exportPath)
  const roundTrip = JSON.parse(await readFile(exportPath, 'utf8'))
  assert.deepEqual(roundTrip.resources.map(resource => resource.path), ['measurements.csv', 'samples.csv'])
  await page.locator('[data-rd-resource="0"]').click()
  await page.locator('[data-rd-grid] tbody tr').first().waitFor()
  await page.setViewportSize({ width: 720, height: 1000 })
  await page.screenshot({ path: path.join(output, 'narrow.png'), fullPage: true })
  assert.equal(await page.locator('#research-file-browser').isVisible(), false)
  await page.locator('[data-rd-browser-toggle]').click()
  assert.equal(await page.locator('#research-file-browser').isVisible(), true)
  assert.equal(await page.locator('[data-rd-open]').isVisible(), true)
  assert.equal(await page.locator('[data-rd-sheet]').evaluate(element => element.scrollWidth <= element.clientWidth + 2), true)
  await page.setViewportSize({ width: 1440, height: 1100 })
  const choosing = page.waitForEvent('filechooser'); await page.locator('[data-rd-import]').click()
  const chooser = await choosing; await chooser.setFiles([path.join(data, 'measurements.csv'), path.join(data, 'samples.csv')])
  await page.waitForFunction(() => document.querySelector('[data-rd-folder-name]')?.textContent === 'Selected files')
  await page.locator('[data-rd-entry="samples.csv"]').click()
  await page.locator('[data-rd-setup]').waitFor({ state: 'visible' })
  await page.locator('[data-rd-field-type="0"]').selectOption('integer')
  await page.locator('[data-rd-apply-schema]').click()
  await page.waitForFunction(() => document.querySelector('[data-rd-grid]')?.textContent.includes('North'))
  assert.equal(await page.locator('[data-rd-grid] tbody tr').count(), 2)
  const partitioned = path.join(output, 'partitioned'); await mkdir(partitioned)
  const parts = Array.from({ length: 12 }, (_, index) => `part-${index}.csv`)
  await Promise.all(parts.map((name, index) => writeFile(path.join(partitioned, name), `id,value\n${index},${index * 10}\n`)))
  await writeFile(path.join(partitioned, 'datapackage.json'), JSON.stringify({ resources: [{ name: 'partitioned', path: parts, schema: { fields: [{ name: 'id', type: 'integer' }, { name: 'value', type: 'number' }] } }] }))
  const nextChooser = page.waitForEvent('filechooser'); await page.locator('[data-rd-import]').click()
  await (await nextChooser).setFiles([path.join(partitioned, 'datapackage.json'), ...parts.map(name => path.join(partitioned, name))])
  await page.waitForFunction(() => document.querySelector('[data-rd-sheet-title]')?.textContent === 'partitioned' && document.querySelector('.rd-workspace')?.getAttribute('aria-busy') === 'false')
  await page.locator('[data-rd-part-filter]').fill('part-11')
  assert.equal(await page.locator('[data-rd-part] option').count(), 2)
  assert.equal(await page.locator('[data-rd-part]').inputValue(), '0')
  await page.locator('[data-rd-part]').selectOption('11')
  await page.waitForFunction(() => document.querySelector('[data-rd-grid] tbody tr td')?.textContent === '11')
  const assessed = path.join(output, 'assessed'); await mkdir(assessed)
  await writeFile(path.join(assessed, 'good.csv'), 'captured_at,reading\n2026-02-01T00:00:00Z,1\n2026-02-01T00:01:00Z,2\n')
  await writeFile(path.join(assessed, 'bad.csv'), 'captured_at,reading\n2026-02-02T00:00:00Z,0\n2026-02-02T00:01:00Z,0\n')
  await writeFile(path.join(assessed, 'quality.csv'), 'resource,path,verdict,reason,measured_metric,measured_value\nsessions,bad.csv,excluded,no two-sided quotes in this session,two_sided_share,0\n')
  await writeFile(path.join(assessed, 'datapackage.json'), JSON.stringify({ name: 'assessed', toolsenabled: { sourceQuality: 'quality-notes' }, resources: [
    { name: 'sessions', path: ['good.csv', 'bad.csv'], schema: { fields: [{ name: 'captured_at', type: 'datetime' }, { name: 'reading', type: 'number' }] } },
    { name: 'quality-notes', path: 'quality.csv', schema: { fields: ['resource', 'path', 'verdict', 'reason', 'measured_metric'].map(name => ({ name, type: 'string' })).concat({ name: 'measured_value', type: 'number' }) } },
  ] }))
  const assessedChooser = page.waitForEvent('filechooser'); await page.locator('[data-rd-import]').click()
  await (await assessedChooser).setFiles(['datapackage.json', 'good.csv', 'bad.csv', 'quality.csv'].map(name => path.join(assessed, name)))
  await page.waitForFunction(() => document.querySelector('[data-rd-sheet-title]')?.textContent === 'sessions' && document.querySelector('.rd-workspace')?.getAttribute('aria-busy') === 'false')
  assert.equal(await page.locator('[data-rd-sheet-flag]').isVisible(), false, 'a file with no recorded verdict is not marked either way')
  await page.locator('[data-rd-part]').selectOption('1')
  // Wait on the data, not on the marker, so a missing marker fails by name.
  await page.waitForFunction(() => document.querySelector('[data-rd-grid] tbody tr td')?.textContent.startsWith('2026-02-02'))
  assert.equal(await page.locator('[data-rd-sheet-flag]').isVisible(), true, 'a file the package marks excluded must say so in its sheet heading')
  assert.match(await page.locator('[data-rd-sheet-flag]').innerText(), /excluded/i, 'the recorded exclusion reaches the sheet heading')
  assert.equal(await page.locator('.rd-sheet-heading [data-rd-sheet-flag]').count(), 1, 'the marker sits in the sheet heading, not only in the panel below')
  assert.match(await page.locator('[data-rd-quality]').innerText(), /no two-sided quotes in this session/, 'the recorded reason is shown verbatim')
  await page.screenshot({ path: path.join(output, 'excluded-heading.png'), fullPage: true })
  await page.locator('[data-rd-part]').selectOption('0')
  await page.waitForFunction(() => document.querySelector('[data-rd-grid] tbody tr td')?.textContent.startsWith('2026-02-01'))
  assert.equal(await page.locator('[data-rd-sheet-flag]').isVisible(), false, 'the marker clears when an unassessed file is shown')
  // A verdict the package spells its own way still has to reach the heading.
  // "superseded" is not one of the spellings this page was first written
  // around, and a dataset that uses it has not said its file is sound.
  const spellings = path.join(output, 'spellings'); await mkdir(spellings)
  await writeFile(path.join(spellings, 'first.csv'), 'captured_at,reading\n2026-04-01T00:00:00Z,1\n')
  await writeFile(path.join(spellings, 'second.csv'), 'captured_at,reading\n2026-04-02T00:00:00Z,2\n')
  await writeFile(path.join(spellings, 'quality.csv'), 'resource,path,verdict,reason\nsessions,first.csv,superseded,replaced by the 2026 revision\nsessions,second.csv,pass,within tolerance\n')
  const spellingFields = ['resource', 'path', 'verdict', 'reason'].map(name => ({ name, type: 'string' }))
  await writeFile(path.join(spellings, 'datapackage.json'), JSON.stringify({ name: 'spellings', toolsenabled: { sourceQuality: 'quality-notes' }, resources: [
    { name: 'sessions', path: ['first.csv', 'second.csv'], schema: { fields: [{ name: 'captured_at', type: 'datetime' }, { name: 'reading', type: 'number' }] } },
    { name: 'quality-notes', path: 'quality.csv', schema: { fields: spellingFields } },
  ] }))
  const spellingChooser = page.waitForEvent('filechooser'); await page.locator('[data-rd-import]').click()
  await (await spellingChooser).setFiles(['datapackage.json', 'first.csv', 'second.csv', 'quality.csv'].map(name => path.join(spellings, name)))
  await page.waitForFunction(() => document.querySelector('[data-rd-grid] tbody tr td')?.textContent.startsWith('2026-04-01'))
  assert.equal(await page.locator('[data-rd-sheet-flag]').isVisible(), true, 'a verdict spelled outside the original list still marks the heading')
  assert.match(await page.locator('[data-rd-sheet-flag]').innerText(), /superseded/i, 'the heading shows the spelling the package used')
  await page.locator('[data-rd-part]').selectOption('1')
  await page.waitForFunction(() => document.querySelector('[data-rd-grid] tbody tr td')?.textContent.startsWith('2026-04-02'))
  assert.equal(await page.locator('[data-rd-sheet-flag]').isVisible(), false, 'a cleared file is still cleared')

  // Both sizes this page used to refuse outright: more than ten thousand rows
  // of notes, and more than eight mebibytes of them.
  const large = path.join(output, 'large'); await mkdir(large)
  await writeFile(path.join(large, 'a.csv'), 'captured_at,reading\n2026-05-01T00:00:00Z,1\n')
  const padded = 'r'.repeat(280), bigRows = 30000
  const bigNotes = 'resource,path,verdict,reason\n' + `sessions,a.csv,provisional,${padded}\n`.repeat(bigRows)
  assert.ok(bigNotes.length > 8 * 1024 * 1024 && bigRows > 10000, `the fixture is past both former limits: ${bigNotes.length} bytes, ${bigRows} rows`)
  await writeFile(path.join(large, 'quality.csv'), bigNotes)
  await writeFile(path.join(large, 'datapackage.json'), JSON.stringify({ name: 'large', toolsenabled: { sourceQuality: 'quality-notes' }, resources: [
    { name: 'sessions', path: ['a.csv'], schema: { fields: [{ name: 'captured_at', type: 'datetime' }, { name: 'reading', type: 'number' }] } },
    { name: 'quality-notes', path: 'quality.csv', schema: { fields: spellingFields } },
  ] }))
  const largeChooser = page.waitForEvent('filechooser'); await page.locator('[data-rd-import]').click()
  await (await largeChooser).setFiles(['datapackage.json', 'a.csv', 'quality.csv'].map(name => path.join(large, name)))
  await page.waitForFunction(() => document.querySelector('[data-rd-grid] tbody tr td')?.textContent.startsWith('2026-05-01'), null, { timeout: 120000 })
  const qualityText = await page.locator('[data-rd-quality]').innerText()
  assert.match(qualityText, /30[,. ]?000 recorded notes read in full/, `the panel states the complete reading: ${qualityText.slice(0, 200)}`)
  assert.equal(qualityText.includes('could not be read'), false, 'a large assessment is read, not refused')
  assert.equal(await page.locator('[data-rd-sheet-flag]').isVisible(), true, 'every one of those notes still marks the heading')
  await page.screenshot({ path: path.join(output, 'large-quality.png'), fullPage: true })
  // A sheet whose only text column never varies: the grouping prompt cannot see
  // it, so the default-line refusal is the only thing between a person who has
  // chosen nothing and a line drawn through simultaneous records.
  const simultaneous = path.join(output, 'simultaneous'); await mkdir(simultaneous)
  await writeFile(path.join(simultaneous, 'readings.csv'), 'venue,captured_at,reading\nACME,2026-03-01T00:00:00Z,10\nACME,2026-03-01T00:00:00Z,30\nACME,2026-03-01T00:01:00Z,11\nACME,2026-03-01T00:01:00Z,31\n')
  await writeFile(path.join(simultaneous, 'datapackage.json'), JSON.stringify({ name: 'simultaneous', resources: [
    { name: 'readings', path: 'readings.csv', schema: { fields: [{ name: 'venue', type: 'string' }, { name: 'captured_at', type: 'datetime' }, { name: 'reading', type: 'number' }] } },
  ] }))
  const simChooser = page.waitForEvent('filechooser'); await page.locator('[data-rd-import]').click()
  await (await simChooser).setFiles(['datapackage.json', 'readings.csv'].map(name => path.join(simultaneous, name)))
  await page.waitForFunction(() => document.querySelector('[data-rd-sheet-title]')?.textContent === 'readings' && document.querySelector('.rd-workspace')?.getAttribute('aria-busy') === 'false')
  await page.locator('[data-rd-tab="chart"]').click()
  await page.waitForFunction(() => document.querySelector('[data-rd-chart-note]')?.textContent.includes('simultaneous'))
  assert.equal(await page.locator('[data-rd-chart] svg').count(), 0, 'the default line is refused, not drawn through simultaneous records')
  assert.match(await page.locator('[data-rd-chart-note]').innerText(), /Choose Scatter/, 'the refusal names the way out')
  await page.locator('[data-rd-chart-kind]').selectOption('scatter')
  await page.locator('[data-rd-chart] svg').waitFor()
  assert.equal(await page.locator('[data-rd-chart] svg').count(), 1, 'scatter implies no order, so it draws')
  await page.locator('[data-rd-series]').selectOption('all')
  await page.locator('[data-rd-chart-kind]').selectOption('line')
  await page.locator('[data-rd-chart] svg').waitFor()
  assert.equal(await page.locator('[data-rd-chart] svg').count(), 1, 'an explicit all-rows choice is still honoured')
  assert.deepEqual(errors.filter(message => /research-data|readTable|createDataChart/.test(message)), [])
  const report = { ok: true, output, checks: ['folder connection origin/path/method boundaries', 'package import', 'typed sheet', 'HTML escaping', 'pagination', 'type error location', 'filter', 'chart', 'explicit series grouping prevents mixed lines', 'whole-file validation', 'text preview', 'CSV schema editor', 'multiple sheets preserved on import and export', 'standard descriptor export', 'narrow layout and folder drawer', 'Import files through the file chooser', 'partition filename search preserves current file until selection', 'a recorded source-quality exclusion is marked in the sheet heading', 'a verdict spelled outside the original list still marks the heading', 'a quality resource past the former row and byte limits is read in full', 'the default line refuses to join simultaneous records and names Scatter'], unrelatedPageErrors: errors }
  await writeFile(path.join(output, 'report.json'), JSON.stringify(report, null, 2) + '\n')
  console.log(JSON.stringify(report, null, 2))
} finally { await browser?.close(); await new Promise(resolve => server.close(resolve)) }
