// WHAT THE SUBSCRIPTION PAGE IS ALLOWED TO SAY, READ FROM THE ONE PLACE THAT
// DECIDES IT.
//
// /data/subscription-catalog.json is generated by tools/gen-subscription-catalog.mjs
// out of the engine's src/lib/entitlement.js. This module fetches it and hands
// the page either a catalog or a REASON -- never a partial one, never a default,
// and never an empty plan list dressed as "no plans available".
//
// AND ON A PACKAGED BUILD IT IS NOT THERE, WHICH IS THE POINT. R1214: the
// catalog shipped a Team price and a three-seat minimum the owner never
// authorised, into a release whose rule is "we are NOT collecting payments at
// first public launch". The answer was not a flag on this module -- a flag can
// be turned on -- but the bytes: config/renderer-payload-boundary.json
// classifies data/subscription-catalog.json as `withheld`, the generated file
// lives at config/subscription-catalog.json outside the payload, and
// tools/check-renderer-payload.mjs fails the build if one reappears under
// public/. So this reader's 404 branch is the SHIPPED path, not the edge case:
// the page renders "Subscriptions are not open yet" with no plan, no price, no
// seat minimum and no purchase control. The validation below is unchanged and
// is not what enforces the owner's rule; it is what stops a DAMAGED catalog
// being rendered on the day one is served again.
//
// ABSENCE FAILS CLOSED, AND THIS IS THE PAGE WHERE THAT MATTERS MOST. A missing
// catalog, a 404, a truncated body, an unrecognized schemaVersion, a plan with a
// null price, a plan granting a capability the file does not describe -- every one
// of them returns { ok:false, reason } and the page shows a refusal with its
// signup controls DISABLED. The tempting alternative (show the plans we can parse,
// hide the rest) is the defect: a customer would be charged for a plan assembled
// from a file we already know is damaged.
//
// This module never mutates anything and issues exactly one request.

const CATALOG_URL = '/data/subscription-catalog.json'
const SCHEMA_VERSION = 1

function isPlainObject(value) {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value)
}

function nonEmptyString(value) {
  return typeof value === 'string' && value.trim().length > 0
}

/**
 * Validate a parsed catalog. Exported so the same rules run in the browser and
 * in tools/test/subscription-catalog.test.mjs against hand-built damage.
 *
 * @returns {{ok:true,catalog:object}|{ok:false,reason:string}}
 */
export function validateCatalog(data) {
  if (!isPlainObject(data)) return { ok: false, reason: 'the plan catalog is not an object' }
  if (data.schemaVersion !== SCHEMA_VERSION) {
    return { ok: false, reason: `the plan catalog has schemaVersion ${JSON.stringify(data.schemaVersion)}; this page reads ${SCHEMA_VERSION}` }
  }
  for (const field of ['paidProduct', 'unlicensedInstall', 'unlicensedInstallStatement']) {
    if (!nonEmptyString(data[field])) return { ok: false, reason: `the plan catalog is missing ${field}` }
  }
  if (!Array.isArray(data.neverGated) || data.neverGated.length === 0 || !data.neverGated.every(nonEmptyString)) {
    return {
      ok: false,
      // Refusing here rather than rendering the paid column alone is deliberate:
      // a price page that shows what money buys and NOT what is free for ever
      // is the "free tier is a trial" reading the product explicitly refuses.
      reason: 'the plan catalog does not state what is free forever, so the paid plans cannot be shown beside it'
    }
  }
  if (!isPlainObject(data.capabilities)) return { ok: false, reason: 'the plan catalog describes no capabilities' }
  for (const [id, capability] of Object.entries(data.capabilities)) {
    if (!isPlainObject(capability) || !nonEmptyString(capability.label) || !nonEmptyString(capability.rationale)) {
      return { ok: false, reason: `capability "${id}" in the plan catalog has no label or no reason` }
    }
    if (!Array.isArray(capability.requiredTiers) || !capability.requiredTiers.every(nonEmptyString)) {
      return { ok: false, reason: `capability "${id}" names no plans it belongs to` }
    }
    if (!Array.isArray(capability.freeAlternatives) || capability.freeAlternatives.length === 0) {
      return { ok: false, reason: `capability "${id}" names no free alternative` }
    }
  }
  if (!Array.isArray(data.plans) || data.plans.length === 0) {
    return { ok: false, reason: 'the plan catalog lists no plans' }
  }
  for (const plan of data.plans) {
    if (!isPlainObject(plan) || !nonEmptyString(plan.id) || !nonEmptyString(plan.label)) {
      return { ok: false, reason: 'a plan in the catalog has no id or no name' }
    }
    if (!Array.isArray(plan.grants)) return { ok: false, reason: `plan "${plan.id}" has no grants list` }
    for (const id of plan.grants) {
      if (!data.capabilities[id]) {
        return { ok: false, reason: `plan "${plan.id}" includes "${id}", which the catalog does not describe` }
      }
    }
    if (plan.requiresLicense === true) {
      if (!Number.isFinite(plan.monthlyUsd) || plan.monthlyUsd <= 0) {
        return { ok: false, reason: `plan "${plan.label}" is a paid plan with no price` }
      }
      if (!nonEmptyString(plan.productId)) {
        return { ok: false, reason: `plan "${plan.label}" cannot be mapped to anything that issues a licence` }
      }
    }
  }
  if (!data.plans.some(plan => plan.requiresLicense === true)) {
    return { ok: false, reason: 'the catalog offers nothing to subscribe to' }
  }
  return { ok: true, catalog: data }
}

/** Fetch and validate the catalog once. Never throws; never invents a plan. */
export async function fetchSubscriptionCatalog({ fetchImpl, url = CATALOG_URL } = {}) {
  const doFetch = fetchImpl || (typeof fetch === 'function' ? fetch : null)
  if (!doFetch) return { ok: false, reason: 'this browser cannot fetch the plan catalog' }
  let response
  try {
    response = await doFetch(url, { cache: 'no-store' })
  } catch (error) {
    return { ok: false, reason: `the plan catalog could not be reached (${error?.message || error})`, offline: true }
  }
  if (!response?.ok) {
    return { ok: false, reason: `the plan catalog responded ${response?.status ?? 'with nothing'} ${response?.statusText || ''}`.trim() }
  }
  let data
  try {
    data = await response.json()
  } catch (error) {
    return { ok: false, reason: `the plan catalog did not parse (${error?.message || error})` }
  }
  return validateCatalog(data)
}

/** The plans a visitor can actually buy, cheapest first. Free plans excluded. */
export function purchasablePlans(catalog) {
  return catalog.plans
    .filter(plan => plan.requiresLicense === true)
    .slice()
    .sort((a, b) => a.monthlyUsd - b.monthlyUsd)
}

/** The free plan, if the catalog declares one. */
export function freePlan(catalog) {
  return catalog.plans.find(plan => plan.requiresLicense !== true) || null
}

/**
 * The inclusion lines for one plan -- the ONLY source of "what you get" text on
 * the page. Derived from the plan's own grants, described by the catalog's own
 * capability entries. There is deliberately no parameter here for adding a line.
 */
export function planInclusions(catalog, plan) {
  return plan.grants.map(id => catalog.capabilities[id]).filter(Boolean)
}
